<a href="https://colab.research.google.com/github/parksuejin1026/2026_BDA_Study/blob/main/Week4/2026_BDA_Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [285]:
import numpy as np

In [286]:
a = np.arange(6).reshape(3, 2) # 0부터 5까지의 숫자로 3행 2열 배열 생성
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [287]:
b = np.arange(6, 12).reshape(3, 2) # 6부터 11까지의 숫자로 3행 2열 배열 생성
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [288]:
np.vstack((a, b)) # 두 배열을 수직으로(행 방향으로) 쌓아 새로운 배열 생성

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [289]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x,y)) # 두 1차원 배열을 수직으로(행 방향으로) 쌓아 2차원 배열 생성

array([[1, 2, 3],
       [5, 6, 7]])

In [290]:
a = np.arange(6).reshape(3, 2) # 0부터 5까지의 숫자로 3행 2열 배열 생성
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [291]:
b = np.arange(10, 19).reshape(3, 3) # 10부터 18까지의 숫자로 3행 3열 배열 생성
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [292]:
np.hstack((a,b)) # 두 배열을 수평으로(열 방향으로) 쌓아 새로운 배열 생성 (행의 개수가 같아야 함)

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [293]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [294]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis])) # np.newaxis로 1차원 배열을 2차원 열 벡터로 변환 후 수평으로 쌓기

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [295]:
x[:, np.newaxis] # 1차원 배열 x를 2차원 열 벡터로 변환

array([[1],
       [2],
       [3]])

In [296]:
np.hstack((x, y)) # 두 1차원 배열을 수평으로(옆으로) 연결하여 하나의 1차원 배열 생성

array([ 1,  2,  3, 10, 20, 30])

In [297]:
np.column_stack == np.hstack

False

In [298]:
a = np.arange(6).reshape(2, 3) # 0부터 5까지의 숫자로 2행 3열 배열 생성
a

array([[0, 1, 2],
       [3, 4, 5]])

In [299]:
b = np.arange(10, 22).reshape(4, 3) # 10부터 21까지의 숫자로 4행 3열 배열 생성
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [300]:
np.row_stack((a, b)) # 두 배열을 수직으로(행 방향으로) 쌓아 새로운 배열 생성 (np.vstack과 동일, DeprecationWarning 발생 가능)

/tmp/ipykernel_12267/3635033110.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b)) # 두 배열을 수직으로(행 방향으로) 쌓아 새로운 배열 생성 (np.vstack과 동일, DeprecationWarning 발생 가능)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [301]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6]) # 1차원 배열이라면 무조건 열추가
np.concatenate((a, b, c)) # 여러 배열을 주어진 축(axis)을 따라 연결 (기본값: axis=0, 1차원 배열의 경우 단순히 연결)

array([1, 2, 3, 4, 5, 6])

In [302]:
np.concatenate((a, b, c) ,axis = 0) # 여러 1차원 배열을 0번 축을 따라 연결하여 하나의 1차원 배열 생성

array([1, 2, 3, 4, 5, 6])

In [303]:
np.concatenate((a, b, c), axis = None) # 모든 배열의 요소를 평탄화하여 하나의 1차원 배열로 연결

array([1, 2, 3, 4, 5, 6])

In [304]:
x = np.arange(6).reshape(2, 3) # 0부터 5까지의 숫자로 2행 3열 배열 생성
x

array([[0, 1, 2],
       [3, 4, 5]])

In [305]:
y = np.arange(10, 16).reshape(2, 3) # 10부터 15까지의 숫자로 2행 3열 배열 생성
y

array([[10, 11, 12],
       [13, 14, 15]])

In [306]:
z = np.arange(20, 24).reshape(2, 2) # 20부터 25까지의 숫자로 2행 3열 배열 생성
z

array([[20, 21],
       [22, 23]])

In [307]:
np.concatenate((x, y)) # 행을 기준으로 쌓기 (axis=0이 기본값) 2차원 배열이라면 행 추가가 default

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [308]:
np.concatenate((x, y), axis = 1) # 열을 기준으로 쌓기

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [309]:
np.concatenate((x, y, z), axis = 1) # 세 배열을 열을 기준으로 쌓기

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [310]:
np.concatenate((x, y), axis = None) # 모든 배열의 요소를 평탄화하여 1차원 배열로 만들기

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [311]:
a = np.array([1, 2, 3]) # 1차원 배열 생성
a

array([1, 2, 3])

In [312]:
b = np.array([4, 5, 6]) # 1차원 배열 생성
b

array([4, 5, 6])

In [313]:
np.stack((a, b)) # 두 1차원 배열을 새로운 축(0번 축)을 따라 쌓아 2차원 배열 생성 (vstack과 유사한 결과)

array([[1, 2, 3],
       [4, 5, 6]])

In [314]:
np.stack((a, b), axis = 1) # 행을 기준으로 담 쌓기: a, b 각각 열로 만들고 열 쌓기 (새로운 축이 1번 축에 추가)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [315]:
np.stack((a, b), axis = -1) # -1은 마지막 축을 의미하며, 이 경우 1과 동일하게 새로운 축이 1번 축에 추가

array([[1, 4],
       [2, 5],
       [3, 6]])

In [316]:
np.arange(1, 19).reshape(3, 3, 2) # 1부터 18까지의 숫자로 3차원 배열 생성 (3개의 3행 2열 배열로 구성됨)
# axis = 0 은 (3, 3, 2)에서 3을 의미함

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [317]:
np.arange(16).reshape(2, 2, 4) # 0부터 15까지의 숫자로 3차원 배열 생성 (2개의 2행 4열 배열로 구성됨)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [318]:
x = np.arange(6).reshape(2, 3)
print(x)
y = np.arange(10, 16).reshape(2, 3)
print(y)
z = np.arange(20, 26).reshape(2, 3)
print(z)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[20 21 22]
 [23 24 25]]


In [319]:
ax0 = np.stack((x, y, z) , axis = 0) # 세 2차원 배열을 새로운 0번 축을 따라 쌓아 3차원 배열 생성 (배열 전체를 하나의 '층'으로)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [320]:
ax0.shape # 배열의 형태 (튜플로 반환: (층의 개수, 행의 개수, 열의 개수))

(3, 2, 3)

In [321]:
ax1 = np.stack((x, y, z), axis = 1) # 세 2차원 배열의 각 행을 묶어서 새로운 1번 축을 따라 쌓아 3차원 배열 생성
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [322]:
ax1.shape # 배열의 형태 (튜플로 반환: (원래 행의 개수, 쌓인 배열의 개수, 원래 열의 개수))

(2, 3, 3)

In [323]:
ax2 = np.stack((x, y, z) , axis =2) # 세 2차원 배열의 각 요소를 묶어서 새로운 2번 축을 따라 쌓아 3차원 배열 생성
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [324]:
ax2.shape # 배열의 형태 (튜플로 반환: (원래 행의 개수, 원래 열의 개수, 쌓인 배열의 개수))

(2, 3, 3)

In [325]:
print(x, '\n')
print(y, '\n')
print(z, '\n')

[[0 1 2]
 [3 4 5]] 

[[10 11 12]
 [13 14 15]] 

[[20 21 22]
 [23 24 25]] 



In [326]:
print('np.stack((x, y, z), axis =0)') # 순서대로 유지
print(np.stack((x, y, z), axis =0))
print('np.stack((x, y, z), axis =1)') # 각 배열의 행들을 모아 3차원 배열 2개 생성
print(np.stack((x, y, z), axis =1))
print('np.stack((x, y, z), axis =2)') # 각 배열들의 행들을 모아 각 행으로 제작 후 3차원 배열 2개 생성
print(np.stack((x, y, z), axis =2))

np.stack((x, y, z), axis =0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis =1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis =2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [327]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [328]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [329]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [330]:
x[:, :, np.newaxis] # 3차원 배열로 만듦

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [331]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [332]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [333]:
np.expand_dims(x, axis = 2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [334]:
np.expand_dims(y, axis = 2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [335]:
np.expand_dims(z, axis = 2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [336]:
np.stack((x, y, z), axis = 2) # expand_dims를 실행한 후 각각의 열에 집어넣는 게 np.stack, axis = 2임

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [337]:
a = np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [338]:
c = np.arange(1, 6, 2).reshape(3,)
c

array([1, 3, 5])

In [339]:
np.hstack((a, np.expand_dims(c, axis = 1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [340]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [341]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [342]:
np.row_stack((a, b))

/tmp/ipykernel_12267/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [343]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [344]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.c_[a, b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [345]:
np.column_stack((a, b)) # 1차원 배열이라 행추가 수직 스택임

array([[1, 4],
       [2, 5],
       [3, 6]])

In [346]:
np.r_['-1, 2, 0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [347]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [348]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [349]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [350]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [351]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [352]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [353]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [354]:
np.row_stack((a, b))

/tmp/ipykernel_12267/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [355]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [356]:
np.r_[3:10:3, [0]*2, 5, 6] # 하나의 행을 추가하는 거임

array([3, 6, 9, 0, 0, 5, 6])

In [357]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [358]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [359]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [360]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [361]:
u = np.r_['0', a, a] # 2차원 배열 a의 axis = 0 행임 따라서
print(u)
u.shape # shpae를 하면 4,3

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


(4, 3)

In [362]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [363]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

# 4.2 배열 분리

In [364]:
a = np.arange(9.0)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [365]:
s = np.split(a, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [366]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [367]:
np.split(y, [2, 3, 4, 6]) # 인덱스 기준 y 배열을 [0,2), [2,3) , [3, 4), [4,6) 으로 나눈다는 의미

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [368]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [369]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [370]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [371]:
np.split(a, 3, axis = 1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [372]:
np.split(a, 4, axis = 1) # 12열이니까 3열씩 가져감

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [373]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [374]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [375]:
np.split(b, 3, axis = 0) # 행을 기준으로 나눈다 b 배열의 행은 총 6개니까 2개씩 나눔

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [376]:
np.split(b, [2, 4, 6], axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [377]:
a = np.arange(24).reshape(2, 12) # axis[0]은 2개 axis[1]은 12개
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [378]:
np.split(a, [3, 5, 7], axis = 1) # [0,3) [3,5) [5,7) [7,-1] 까지 총 4개로 나뉨

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [379]:
b =  np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [380]:
np.split(b, 3, axis = 0) # 행은 총 6개니까 개당 3개의 배열을 각 (2,4) 배열로 나눔

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [381]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [382]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [383]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [384]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [385]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [386]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [387]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [388]:
np.vsplit(a, 4) # 6은 4로 나누면 정수가 아니라 안됨

ValueError: array split does not result in an equal division

In [389]:
a = np.arange(18).reshape(6, 3)

In [390]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [391]:
a[:1, :] # 0번째 행과 모든 열

array([[0, 1, 2]])

In [392]:
a[4:6, :] # 4~5번째 행과 모든 열

array([[12, 13, 14],
       [15, 16, 17]])

In [393]:
a[6:, :] # 6번째 행과 모든 열 마지막 배열은 요소는 존재 x 하지만 모양과 데이터 타입을 반환해줌

array([], shape=(0, 3), dtype=int64)

In [394]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [395]:
np.vsplit(x, 2) # 행을 기즌으로 이등분해서 배열 분리함

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [396]:
np.split(x, 2 , axis = 0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [397]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [398]:
x[:1, :,:]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [399]:
x[1:3, :, :]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [400]:
x[3:,:, :]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [401]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [402]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [403]:
np.split(x, 2, axis = 1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [404]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

## numpy의 난수와 다양한 함수

In [405]:
rg = np.random.default_rng(12345) # 난수 생성기를 초기화하고 seed 값 설정 (재현 가능하도록)
rg

Generator(PCG64) at 0x7FB3038C0E40

In [406]:
r = rg.random() # 0 이상 1 미만의 실수 난수 하나 생성
r

0.22733602246716966

In [407]:
rg.random(5) # 0 이상 1 미만의 실수 난수 5개로 구성된 1차원 배열 생성

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [408]:
rg.random((4, 3)) # 0 이상 1 미만의 실수 난수로 구성된 4행 3열 배열 생성

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [409]:
rg = np.random.default_rng(12345) # 난수 생성기를 초기화하고 seed 값 설정
r = rg.integers(low = 0, high = 10, size = 3) # low(포함)부터 high(미포함) 사이의 정수 난수 3개 생성
r

array([6, 2, 7])

In [410]:
rg.integers(1, 7, (3,4)) # 1(포함)부터 7(미포함) 사이의 정수 난수로 구성된 3행 4열 배열 생성

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [411]:
rg = np.random.default_rng(seed = 42) # 난수 생성기를 초기화하고 seed 값 설정
rg.standard_normal(10) # 표준 정규 분포(평균 0, 표준편차 1)를 따르는 실수 난수 10개 생성

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [412]:
rg.standard_normal((4, 3)) # 표준 정규 분포를 따르는 실수 난수로 구성된 4행 3열 배열 생성

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])

In [413]:
rg.standard_normal((10, 6)) # 표준 정규 분포를 따르는 실수 난수로 구성된 10행 6열 배열 생성

array([[ 1.22254134, -0.15452948, -0.42832782, -0.35213355,  0.53230919,
         0.36544406],
       [ 0.41273261,  0.430821  ,  2.1416476 , -0.40641502, -0.51224273,
        -0.81377273],
       [ 0.61597942,  1.12897229, -0.11394746, -0.84015648, -0.82448122,
         0.65059279],
       [ 0.74325417,  0.54315427, -0.66550971,  0.23216132,  0.11668581,
         0.2186886 ],
       [ 0.87142878,  0.22359555,  0.67891356,  0.06757907,  0.2891194 ,
         0.63128823],
       [-1.45715582, -0.31967122, -0.47037265, -0.63887785, -0.27514225,
         1.49494131],
       [-0.86583112,  0.96827835, -1.68286977, -0.33488503,  0.16275307,
         0.58622233],
       [ 0.71122658,  0.79334724, -0.34872507, -0.46235179,  0.85797588,
        -0.19130432],
       [-1.27568632, -1.13328721, -0.91945229,  0.49716074,  0.14242574,
         0.69048535],
       [-0.42725265,  0.15853969,  0.62559039, -0.30934654,  0.45677524,
        -0.66192594]])

In [414]:
x = rg.standard_normal((10, 6))
for i in x:
 # 배열 i에서 2.0 이상인 요소가 하나라도 있는지 확인
 if (i >= 2.0).any():
  print(i)

[ 0.31351385  0.83812657  1.99673089  2.91386247  0.41440943 -0.98953812]


In [415]:
a = np.arange(1, 4) # 1부터 3까지의 숫자로 1차원 배열 생성
b = np.arange(4, 7) # 4부터 6까지의 숫자로 1차원 배열 생성
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [416]:
c = np.arange(1, 7).reshape(2, 3) # 1부터 6까지의 숫자로 2행 3열 배열 생성
d = np.arange(7,13).reshape(2, 3) # 7부터 12까지의 숫자로 2행 3열 배열 생성
c, d

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [417]:
np.vstack((a, b)) # 1차원 배열을 2차원 배열로 만들면서 수직으로 쌓기

array([[1, 2, 3],
       [4, 5, 6]])

In [418]:
np.hstack((a, b)) # 1차원 배열들을 수평으로 연결하여 하나의 1차원 배열로 확장

array([1, 2, 3, 4, 5, 6])

In [419]:
np.vstack((c, d)) # 두 2차원 배열을 수직으로(행 방향으로) 쌓기

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [420]:
np.hstack((c, d)) # 두 2차원 배열을 수평으로(열 방향으로) 쌓기

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [421]:
np.column_stack((a, b)) # 두 1차원 배열을 열로 간주하여 수평으로 쌓아 2차원 배열 생성

array([[1, 4],
       [2, 5],
       [3, 6]])

In [422]:
np.column_stack((a, b)), np.c_[a, b] # np.column_stack과 np.c_는 동일한 기능 (열 방향으로 배열 쌓기)을 제공

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [423]:
np.arange(24).reshape(2, 3, 4) # 0부터 23까지의 숫자로 3차원 배열 생성 (2개의 3행 4열 배열로 구성됨)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [424]:
n = np.arange(96).reshape(4,4,6) # 0부터 95까지의 숫자로 4개의 4행 6열 배열을 가진 3차원 배열 생성

In [425]:
np.split(n, 2, axis = 2) # 배열 n을 2번 축(가장 안쪽 축)을 기준으로 2개로 분할

[array([[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14],
         [18, 19, 20]],
 
        [[24, 25, 26],
         [30, 31, 32],
         [36, 37, 38],
         [42, 43, 44]],
 
        [[48, 49, 50],
         [54, 55, 56],
         [60, 61, 62],
         [66, 67, 68]],
 
        [[72, 73, 74],
         [78, 79, 80],
         [84, 85, 86],
         [90, 91, 92]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17],
         [21, 22, 23]],
 
        [[27, 28, 29],
         [33, 34, 35],
         [39, 40, 41],
         [45, 46, 47]],
 
        [[51, 52, 53],
         [57, 58, 59],
         [63, 64, 65],
         [69, 70, 71]],
 
        [[75, 76, 77],
         [81, 82, 83],
         [87, 88, 89],
         [93, 94, 95]]])]