<a href="https://colab.research.google.com/github/parksuejin1026/2026_BDA_Study/blob/main/Week4/2026_BDA_Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [6]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [10]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [11]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [12]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [13]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [14]:
np.column_stack == np.hstack

False

In [16]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [20]:
np.row_stack((a, b))

/tmp/ipykernel_4235/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [23]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [27]:
np.concatenate((a, b, c) ,axis = 0)

array([1, 2, 3, 4, 5, 6])

In [28]:
np.concatenate((a, b, c), axis = None)

array([1, 2, 3, 4, 5, 6])

In [29]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [31]:
z = np.arange(20, 24).reshape(2, 2)

In [32]:
np.concatenate((x, y)) # 행을 기준으로 쌓기

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [33]:
np.concatenate((x, y), axis = 1) #  열을 기준으로 쌓기

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [35]:
np.concatenate((x, y, z), axis = 1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [36]:
np.concatenate((x, y), axis = None) # 1차원 배열로 만들어버리기

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [37]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [38]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [39]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.stack((a, b), axis = 1) # 행을 기준으로 담 쌓기 a, b 각각 열로 만들고 열 쌓기

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
np.stack((a, b), axis = -1) # -1 은 1과 동일함

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
np.arange(1, 19).reshape(3, 3, 2) # 3행 2열 2차원 배열 3개 생성 axis = 0 은 3개

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [43]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [45]:
x = np.arange(6).reshape(2, 3)
print(x)
y = np.arange(10, 16).reshape(2, 3)
print(y)
z = np.arange(20, 26).reshape(2, 3)
print(z)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[20 21 22]
 [23 24 25]]


In [50]:
ax0 = np.stack((x, y, z) , axis = 0) # 이렇게하면 행렬끼리 3차원 배열의 행렬이 됨
ax0

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [51]:
ax0.shape

(2, 3, 3)

In [58]:
ax1 = np.stack((x, y, z), axis = 1) # 행들끼리 결합하여 3차원 배열 총 2개 생성
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [59]:
ax1.shape

(2, 3, 3)

In [60]:
ax2 = np.stack((x, y, z) , axis =2) # x,y,z를 각각 하나의 열로 만들어서 3차원 배열로 생성
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [61]:
ax2.shape

(2, 3, 3)

In [62]:
print(x, '\n')
print(y, '\n')
print(z, '\n')

[[0 1 2]
 [3 4 5]] 

[[10 11 12]
 [13 14 15]] 

[[20 21 22]
 [23 24 25]] 



In [63]:
print('np.stack((x, y, z), axis =0)')
print(np.stack((x, y, z), axis =0))
print('np.stack((x, y, z), axis =1)')
print(np.stack((x, y, z), axis =1))
print('np.stack((x, y, z), axis =2)')
print(np.stack((x, y, z), axis =2))

np.stack((x, y, z), axis =0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis =1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis =2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


## numpy의 난수와 다양한 함수

In [64]:
rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7D661F2D90E0

In [65]:
r = rg.random() # [0~1)
r

0.22733602246716966

In [66]:
rg.random(5) # [0~1) 5개

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [67]:
rg.random((4, 3)) # [0~1) 4행 3열 배열

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [70]:
rg = np.random.default_rng(12345)
r = rg.integers(low = 0, high = 10, size = 3)
r

array([6, 2, 7])

In [71]:
rg.integers(1, 7, (3,4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [72]:
rg = np.random.default_rng(seed = 42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [83]:
rg.standard_normal((4, 3))

array([[-0.3898098 , -1.37668615,  0.63515095],
       [-0.2222227 , -1.47080629, -1.01557908],
       [ 0.31351385,  0.83812657,  1.99673089],
       [ 2.91386247,  0.41440943, -0.98953812]])

In [84]:
rg.standard_normal((10, 6))

array([[-2.13204628,  0.26771146, -0.8129411 , -0.41535726, -0.6120968 ,
        -0.14079089],
       [ 1.06598023,  0.15704857, -0.15863484, -1.03565375, -1.67468294,
        -0.48630791],
       [-0.05378255,  1.76792991,  0.13027452,  0.98273951, -0.4992956 ,
        -1.18494377],
       [-0.96511676, -0.72522606,  2.12846973, -0.82138668,  0.8384892 ,
        -0.90292718],
       [ 0.93157301,  0.38495097, -0.1566379 , -0.04076253, -0.6547877 ,
         0.4460722 ],
       [-0.45498348, -1.22560576, -1.27793757,  0.17258792,  1.57909126,
         0.15999161],
       [-0.11863833,  0.28582614,  1.30600174,  0.2193825 , -0.41092723,
         1.10628871],
       [ 0.42875644,  1.53575599,  0.18323444, -1.22446903, -1.3681592 ,
         1.65092793],
       [ 1.72366572, -0.17951921, -0.38318732,  1.46144429, -1.10704568,
        -0.89472702],
       [ 0.64332679, -0.39460512, -0.00512187, -0.1634429 ,  0.33757455,
         1.40748186]])

In [92]:
x = rg.standard_normal((10, 6))
for i in x:
 if (i >= 2.0).any():
  print(i)

[-1.04058605 -2.41278033  1.610937    2.54932795 -0.40526927 -1.93683804]
[-1.49440562  0.69919673  2.05268498  0.17196033 -0.33732516 -0.14200321]
[ 2.38260228  0.4201886   0.38770314 -0.16692793  0.81677587  0.6250852 ]


In [93]:
a = np.arange(1, 4)
b = np.arange(4, 7)
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [96]:
c = np.arange(1, 7).reshape(2, 3)
d = np.arange(7,13).reshape(2, 3)
c, d

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [97]:
np.vstack((a, b)) # 1D -> 2D

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.hstack((a, b)) # 1D expand

array([1, 2, 3, 4, 5, 6])

In [99]:
np.vstack((c, d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
np.hstack((c, d))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [101]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [104]:
np.column_stack((a, b)),  np.c_[a, b]

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [105]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [108]:
n = np.arange(96).reshape(4,4,6)

In [109]:
np.split(n, 2, axis = 2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14],
         [18, 19, 20]],
 
        [[24, 25, 26],
         [30, 31, 32],
         [36, 37, 38],
         [42, 43, 44]],
 
        [[48, 49, 50],
         [54, 55, 56],
         [60, 61, 62],
         [66, 67, 68]],
 
        [[72, 73, 74],
         [78, 79, 80],
         [84, 85, 86],
         [90, 91, 92]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17],
         [21, 22, 23]],
 
        [[27, 28, 29],
         [33, 34, 35],
         [39, 40, 41],
         [45, 46, 47]],
 
        [[51, 52, 53],
         [57, 58, 59],
         [63, 64, 65],
         [69, 70, 71]],
 
        [[75, 76, 77],
         [81, 82, 83],
         [87, 88, 89],
         [93, 94, 95]]])]